CREATE TABLE feedback (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    reference_id BIGINT NOT NULL,
    reference_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL, -- ACCEPT, ACCEPT_WITH_EDITS, REJECT
    user_comment TEXT,
    edited_output JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
